### ISSUE TITLE
[MKMapView annotationContainer:viewForAnnotation]

### ISSUE THREAD

**Issue by shmidt** [BotiKis/OCMapView#10]
I'm getting crash in my project when adding annotations on map with subject message.
I'm using iOS6 and my annotations are NSManagedObject's

**Comment by BotiKis** [comment]
There is no method called `annotationContainer:viewForAnnotation` in the mapView class.

**Comment by shmidt** [comment]
OK, I find error :)
- (MKAnnotationView *)mapView:(MKMapView *)mapView viewForAnnotation:(id <MKAnnotation>)annotation
  {
  ...
  }
  else if ([annotation isKindOfClass:[NearbyPlace class]]) {
      MKAnnotationView *placeView = nil;
  ...
  
  ```
  }
  else {
      placeView.annotation = annotation;
  }
  return placeView;
  ```
  
  }
  else if ([annotation isKindOfClass:[MKPointAnnotation class]])
  {
      static NSString\* addressAnnotationIdentifier = @"AddPinAnnotationIdentifier";
      ...
      }
      return pinView;
  }
  //    else {
      NSLog([[annotation class]description]);
      return nil;
  //    }

}

When I commented last else, everything worked properly.

**Comment by BotiKis** [comment]
Jup, it is not allowed to return `nil` in the `viewForAnnotation`-Method.
