### ISSUE TITLE
Podspec not in offical CocoaPods repo

### ISSUE THREAD

**Issue by swissmanu** [BotiKis/OCMapView#13]
hi @yinkou!
first things first: thank you for your awesome clustering implementation. really really appreciate your efforts!

i just recognized that your podspec is not present via the offical cocoapods spec repository. if you like, i'd publish it for you.

just let me know :)

cheers,
@swissmanu

**Comment by BotiKis** [comment]
Thanx, i'm going to rework it soon with animation support and improved performance. So stay tuned.
I've also merge the podspec fix and tagged it so it should be on cocoapods.
