### ISSUE TITLE
Showing all pins...

### ISSUE THREAD

**Issue by ghost** [BotiKis/OCMapView#17]
Hello,

Is there a way to show all the pins, but have the ones with the same long/lat display a different color?

I almost have that now, but I do not want it to expand out when I zoom.  I was hoping I could show all the pin, but the ones in the same location get clustered (or grouped) and show a different color indicating multiple people at that address.

Thank you

**Comment by calimarkus** [comment]
With the current implementation you would have two options:
1. a very small `clusterSize`, e.g. `0.01` - perhaps good enough for your usecase
2. use groups. Compare the lat/longs yourself and assign the `groupTag` of your annotations accordingly. Make sure, that `clusterByGroupTag` is YES.
