### ISSUE TITLE
how can i draw line on mkmapview

### ISSUE THREAD

**Issue by erhandemirci** [BotiKis/OCMapView#21]
Hi , 

I want to add line on mapkit. . How can I solve? 

you can see my post .  

http://stackoverflow.com/questions/19339366/how-can-i-draw-line-on-mkmapview

Thank you .

**Comment by calimarkus** [comment]
Just use `displayedAnnotations` (these are only the ones visible) instead of `annotations` (these are all annotations, that were added).
