### ISSUE TITLE
Overlay support?

### ISSUE THREAD

**Issue by wangshengjia** [BotiKis/OCMapView#22]
Hi,

I have exactly the same performance issue for overlays. Is there a easy way to use it with the overlays in stead of the annotations?

Thanks in advance.

**Comment by calimarkus** [comment]
no this is for annotation clustering only. overlays are very custom content and can be used in many ways.. what exactly do you want in your case?

**Comment by wangshengjia** [comment]
Thanks for reply.

Actually, I have thousands small pieces of images(the POI) to add to the map as an overlay. So obviously, there is the performance issue. Do you have any idea about it?

**Comment by calimarkus** [comment]
Just use annotations for this. You can set custom images there. (Use `MKAnnotationView` instead of `MKPinAnnotationView`)

**Comment by wangshengjia** [comment]
Hmm...problem is : we do need them act as an overlay instead of an annotation. For example : the size of them should be changed dynamically with the zoom level of the map.

**Comment by calimarkus** [comment]
perhaps replace the annotations / images according to the zoom level.. but anyway: this class works only with annotations, perhaps you can extract what you need and use it for overlays..

**Comment by wangshengjia** [comment]
I will try it. Thank you anyway : )
