### ISSUE TITLE
Clustering when panning

### ISSUE THREAD

**Issue by gcasilva** [BotiKis/OCMapView#23]
Cluster when panning is broken on new version guys.
I'll make a video later, but just so you can test with the example App, if you make a pan movement the cluster drawing disappears and is appears just after some movements.
This behaviour wasn't like that on the past version.

**Comment by BotiKis** [comment]
Oh that doesn't sound good. @jaydee3 Can you take a look at this?

**Comment by calimarkus** [comment]
fixed, although it was only an example project issue. the visible radius around the clusters is not part of the framework.
