### ISSUE TITLE
mapView:viewForAnnotation: is not being called

### ISSUE THREAD

**Issue by lukaszmargielewski** [BotiKis/OCMapView#3]
I encounter strange problem when using OCMapView. After replacing MKMapView with OCMapView mapView:viewForAnnotation is not being called for my annotations anymore. It is only being called for MKUserLocation.
(I am not using Interface Builder, but allocating by code).
I have also added groupTag property to my annotation class.

What I am doing wrong?

**Comment by lukaszmargielewski** [comment]
OCMapView is missing code inititalizer override method. initSetup is never called when creating map view from code.
I added this function to OCMapView.m:

-(id)initWithFrame:(CGRect)frame{

```
self = [super initWithFrame:frame];

if (self) {
    [self initSetUp];
}
return self;
```

}

**Comment by BotiKis** [comment]
Wow, that's a heavy bug and very dumb of me.
And nobody complained for about a year, funny...

Thank you very much!

**Comment by sharathvatti** [comment]
I am still facing this issue. Can any one please help me with this.
Thanks.
