### ISSUE TITLE
memory leak in OCAlgorithms

### ISSUE THREAD

**Issue by yuun** [BotiKis/OCMapView#5]
Hi, 

First I want to thank all the contributors to this great project !
I believe there is a memory leak in the OCAlgorithms.m file raised also by xcode clang analyser.

Line 137 :
`// check group
    if (grouped && [annotation respondsToSelector:@selector(groupTag)]) {
        if (![clusterAnnotation.groupTag isEqualToString:((id <OCGrouping>)annotation).groupTag]) 
            continue;
    }
    // add annotation to the cluster
    [clusterAnnotation addAnnotation:annotation];
    [clusterAnnotation release];`

There should be `[clusterAnnotation release]` before the `continue` instruction

Thanks again for your great job!

Yunus

**Comment by BotiKis** [comment]
Yes, thank you!
